name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.2.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # Plugin for parsing html
  html: ^0.14.0+3

  # Plugins for parsing css
  csslib: ^0.16.2
  css_colors: ^1.0.2

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^0.10.2

  # Plugins for rendering the <video> tag.
  chewie:
    git: https://github.com/brianegan/chewie.git

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^1.0.0

  # Plugins for rendering the <audio> tag.
  chewie_audio:
    git: https://github.com/Sub6Resources/chewie_audio.git

  # Plugins for rendering the <svg> tag.
  flutter_svg:
    git: https://github.com/dnfield/flutter_svg.git
    
  xml: ^5.0.0-nullsafety.1
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

